### ISSUE TITLE
Re-design  delegation Page on the website.

### ISSUE THREAD

**Issue by AnaFCPreto** [HermesProtocol-io/hermes-protocol#9]
As we cannot change everything simultaneously, we need to start step by step.

For Hermes Protocol website, the Delegation Page needs to be redone. We should mention the places where we already are validators with the buttons to the site to delegate:
Terra V2 and Q blockchain.

We need an area with nice data like how many people are delegating to us and how much in total. we already have functions to calculate in real-time.

Last but not least why should people delegate to us: 
-We are doing an app that is free and useful for the user and this helps us to diminish the costs
-We do giveaways to people that delegate to us
-We will airdrop to people our token when we have it

**Comment by joaocp88** [comment]
Website Design - https://www.figma.com/file/E0iu9bqBQzfbs6BZhCw8Uu/Hermes-Protocol---Delegation-Page?node-id=0%3A1

**Comment by joaofilipe21** [comment]
@AnaFCPreto , Web Design está feito e pronto a ser desenvolvido.
